name: Update Github Stats

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Github Configurations
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "action@github.com"
          git pull

      - name: Format Code
        run: npm run format

      - name: Commit formatted code
        run: |
          git add .
          git commit -m "Code formatted 🎉" || echo 'No changes to commit'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
